language: node_js
node_js:
- 6
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: releases
  api_key:
    secure: EuD4dCecFUI6EyPjsllB8VPcEt1ula6rz52TeL03N2H6RYfT0bD66SaoKGXL8Ddf0WqM+HfjmjqozJoxEqy44w0yS72ULLfx/k/bVjJyx8JYy/u606iMsKg5X+8QeMEXqSfyLNsr8/mU7eybjItLy6SK5OxYAL4KkF03zYdpjmZwwA2RBXzndRZuf+tp/eundtJQ1XNKFLnpoX5U1gZ0MFXuUBCN46aukismBo39qHO2E9juxPaOtMXtYhYuQ5SGZ13Stbt1qwgBGoddGIAEhKgNAufIwzBRhz9u5X1yXkvPl8aD3jc2GYrwtFIjxwOKEURztzLA9ztV3rzoPdnIsFZvuMcq2LCfm9tsOBJ1jjxR9UVf6BWkUt6Dig6Au+bv88/W1T8Npar5UZlSGZAR5PWNlrgZ7Zbt1nNaLVYYXAaG+Tn1JdgfFku7cTfaBu4B8/RXWJA97sQXw7KK2RZ39YN5S/bILGiiLZjqpngbybYPbRyWuVxEp36jFAKo8H32gUkH076QdW/63LT0VH21cg4P9Q4KAQerIMCN16mdTRcF4pLLfucFaVIiHwBO8sQqTiH+DYilqIxNDGdMHeYWHgjb9g5SahBBGPqCJs/OraSmeoGHGoWTRQkVZat31N/8YTt9yREpdt8TovFWaKP/tzw/8/h+BxElKMc6UEobj0o=
  file: dist/skeletonic.min.css
  on:
    repo: reedia/skeletonic
