language: node_js
node_js:
- 6
before_script:
- npm install -g gulp
script: gulp

# This is needed to avoid building all the tags pushed by travis
branches:
  except:
- /^v?\d+\.\d+\.\d+$/

before_install:
  # Create a git tag of the new version to use
  # If package.json major and minor versions match last tag, then increment last tag. Else use package.json major.minor.0.
- "{ sed -nE 's/^[ \\t]*\"version\": \"([0-9]{1,}\\.[0-9]{1,}\\.)[0-9x]{1,}\",$/\\1/p' package.json; git describe --abbrev=0 | sed -E 's/^v([0-9]{1,}\\.[0-9]{1,}\\.)([0-9]{1,})$/\\1 \\2/g'; } | tr \"\\n\" \" \" | awk '{printf($1==$2?\"v\"$2$3+1:\"v\"$1\"0\")}' | xargs -I {} git tag -a {} -m \"{}\"\n"
  # Update package.json based on the git tag we just created
- npm --no-git-tag-version version from-git

# Push the new tag back to GitHub but only if on the master branch
deploy: script
  skip_cleanup: true
  script: git push --tags
  on:
    branch: master
  api_key:
    secure: COroxSGtJLNO3IG9HSGrQIeGb5TBBemK9SO10pCAulFPLcDbQgtmQMOcXOvmOKqqQg9fwhjfw562Nd2B1Qg0/G3A5lYpKXXukCe6T7c3FOWHp5ZoVm1AKQA0cYf4748z1kXh7r+AevXVnr2lTAP99vahCdd9PzUy7hcv2Hru/nn8t6wmQJj4dWlv9w+YfuNBxUYTfNl/TlRPnQjEYHsiPCl4UJdpsmekqB7HTOT+FhZ7KQQdMjxEbe6ayMVxnthGmowOfd5gvr9wZsWFPtv3zBd21b20RqJtWIzCJY/tBFJuV8CjczrBqYop5wTzbREEfW4N34P5FeZvpRYU0P2/3ojmtPFKScPMT+a/gafCsK67sRZNROBj3rIAJV26tJKcfQMJ7LZVAU+r4FzzZQRJyjn1N3DgqX5wyxFS/lnJ7al+6s3FPB2dOcTAssR040eCWjkdbp/4Aflz77JzDSnbel7bcq2vLAptn0qqaYe0BgAGsvKr9DqhWEigpncn26tXL2blUgmdGLnKxPugSavOFDyU0BnWpm2A28WjQxqak+8SuHkQ/0qOi5mEvEioDIgjMXLFwy56ZNlcQRhp59HOa8AjJqowqe7XCiRIAMdybl4amgPSKacNTV5e3uOFEUyqSLE3Hff71LUgDOLLicZ3LTFH6R1Ag3S9lWHDd4sZuvY=
  file: dist/*
  name: Skeletonic v $(date +'%d.%m.%Y')
  skip_cleanup: true
  file_glob: true
  on:
    repo: reedia/skeletonic
env:
  global:
  - secure: YFrLQXgisc/xmu0L3x2XvRsFzHtaJLfBiCOmO0fhMG02GutVTFelNaVjnl+5H8Wmgijm9qMCWvXMlVjK/NwyY7P+Wbop7/jkXKgl1uYiSH5zXUlEMzTgTS2F/JChegDhiO98MKDmSwY41S1wsLm4rCvWsr3QBHiLN533G4+UAsrX8Rr9JYNkEUwxbjjlT0oYhMkjkDT8JtuUEUAYhW394qNR607Sub0dKRSUdyRU3iyXvUpaaaNSDYQP+NcCIqGnG+g8ftYuz0H23ESwPP3hgCwV0aN48yIPUN1yyOFmiz+LCv9KP4/eYY7ghlnXJPUyqDjqPN4hYmDZQhplvlUBHX5OtX+7EqWF79IJHmOqD/0D5/BjHgLEhMYJH32Txze4EWpsAKB0wBjqhSR7jAdH9UckeYMyiM7OdwSr+Mh4r1pmDLlfQnqwH6qt3pGoeZl2QSZkiLoJBXN/faCN+jQ/dR/JPRGQ6CuaVy1kugxqBunsi3RlRKM4xAcp+WGEF4kIxG9O+0OGJf+FHVSCbpkp7JlGsovaUDxF2CdClNEB1WKIslvJk8w4aYCQ9+AGJAQfiIfVmuIhRzKrFmAzzPGkDt0I6tEQa/fdsIOzof0ES1nA4/xWcc/+npMzpycINs1xx+YKROPoUj/05ENhClmKAU1/aDaX50wiE6s/h2X4YNA=
  - secure: YQlSshtvGVQ/papcUZLkXxBHhQrFwlmCKgVSyAm/zYCNbYHF56lmEHEOBi8eA5JeES0S8gAunrx4/Bnt8yM+cZDe9ooeafHkSgpiI6w9d79RrljSt1k83UOHVoYERKaquSHJ24DE0emUFr+SRAmheLyffZfFT3pHTJMYdtpo7ekv/XRxA3i69BY7SWj9N84Nr+5up09OigqowhLJ6oFdHv5fUUvLpQSiijP6PfYHQA/DMwR9hia0U7gTUwFTFdcDj17emyzoMZH22xtsg4TN3HitseeP0ZjzoiKHNnj6QtRMbiO/hf//1Ln7SxPe0I6DcXYQejOlxARvmB3/zjzEilkIUMSjK/B2SDwUiXp4BxdgtxI/myEEYpLYRDosR3LJPOFWLyETG/BJEOVch4+oIDBYAlgPBy6c5U7NpwlTu8YeFTRx+hUpOm/ydj0Ogwz/qo5g1A0JzE5ckRnuUSMJwx/FzYI2IRtPmgPk8s7oJGZ8WMuWTrP0pOUCfnqCXmeHPtJjc8dYw16Gh0VUFHuA71VQM/esSWHokel6XH/5wurQ+zsDrSqxajnWWwAbnDwWvRUa9BaOT0sSoow2syHinm5I7uI/vc6zamXuAWBCfDNb60CGAFls8QB4m3P3lK8G67vXqodLKqpiGrgHaNLH4nNk4oZRId+I5rsBQKl2/Z8=
