language: node_js
node_js:
- 6
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: releases
  api_key:
    secure: mxBO7cLUKXQ2urEi3X49+cHWm/Mw62RJCee4d+Afn2wkmkmow+6x0v8rf7UOOpD+jBSt35enPWjjXNhX5r4QBU6aPty6cNdnIrg5c3bLhI2qOe+KFrtkulL1b5QDuDmLAc/qLwpBrapCfrDZpbpdbfa6t/yiJ/MiQGu2uNNA13aKWi1HetVh8jJFkymT5M1w5KM+SHQdUvg+uvVlj/3Yd7Hd9dQ5aWYf9FKKCB2kTzM0PsFPMeDiqEtBn2SNxJvndmNtFbsCry2oYOkDFWVFEvqPpcTVfpAHDTiFKqvtlyOVTCPSfL6QK5Y+uSrFskcshAqAOl9NPYr1z8yie8/8hN6ELTjm4fddmzolR75Ep8TX2oraEFAQV4jx/gm4IAdJPQY7BuLyyPcEqU5c17ZrZ+WgRVjhnC14xUZlh5Yo3ZxkmsZfUFsGIkNwHzrmpCYQO7l0qKik7SMZKbNCW2BU/nxehT8cKnth/1cPjNUSLLTiEPIWXwS5iqbUmlfoI08vzGXbKKn0wngfGbEnQMcekASVzEHzv2nSG/E8GhZxqOTVN0IZ9bVCgbLUVL/BNQOZJCiz+WeYvwIEJsUWOWh0cYMRBA7+SdazUktjHrsVfKcq3fJn6Kpmz+KZP/t0fI6U/s3qPmnw9FqywLFpZntlnkezya77g0QXwnl7gPcZQzQ=
  file: dist/skeletonic.min.css
  on:
    repo: reedia/skeletonic
env:
  global:
    secure: mxBO7cLUKXQ2urEi3X49+cHWm/Mw62RJCee4d+Afn2wkmkmow+6x0v8rf7UOOpD+jBSt35enPWjjXNhX5r4QBU6aPty6cNdnIrg5c3bLhI2qOe+KFrtkulL1b5QDuDmLAc/qLwpBrapCfrDZpbpdbfa6t/yiJ/MiQGu2uNNA13aKWi1HetVh8jJFkymT5M1w5KM+SHQdUvg+uvVlj/3Yd7Hd9dQ5aWYf9FKKCB2kTzM0PsFPMeDiqEtBn2SNxJvndmNtFbsCry2oYOkDFWVFEvqPpcTVfpAHDTiFKqvtlyOVTCPSfL6QK5Y+uSrFskcshAqAOl9NPYr1z8yie8/8hN6ELTjm4fddmzolR75Ep8TX2oraEFAQV4jx/gm4IAdJPQY7BuLyyPcEqU5c17ZrZ+WgRVjhnC14xUZlh5Yo3ZxkmsZfUFsGIkNwHzrmpCYQO7l0qKik7SMZKbNCW2BU/nxehT8cKnth/1cPjNUSLLTiEPIWXwS5iqbUmlfoI08vzGXbKKn0wngfGbEnQMcekASVzEHzv2nSG/E8GhZxqOTVN0IZ9bVCgbLUVL/BNQOZJCiz+WeYvwIEJsUWOWh0cYMRBA7+SdazUktjHrsVfKcq3fJn6Kpmz+KZP/t0fI6U/s3qPmnw9FqywLFpZntlnkezya77g0QXwnl7gPcZQzQ=
