sudo: false
language: node_js
node_js:
- 6
before_script:
- npm install -g gulp
script: gulp
notifications:
  email: false
after_success:
- export GIT_TAG=v1.0.$TRAVIS_BUILD_NUMBER
- echo -n $GIT_TAG > v0.1.$TRAVIS_BUILD_NUMBER
- git commit -m "Set build VERSION number to "$GIT_TAG
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
- git push --quiet https://$GITHUBKEY@github.com/reedia/skeletonic $GIT_TAG > /dev/null
  2>&1
- echo "${TRAVIS_BRANCH}"
- echo "${TRAVIS_PULL_REQUEST}"
- echo "${TRAVIS_SECURE_ENV_VARS}"
- echo "${TRAVIS_COMMIT}"
- echo ${TRAVIS_BUILD_NUMBER}
- echo ${TRAVIS_REPO_SLUG}
- echo ${GIT_TAG}
before_deploy:
- echo 'Ready to deploy Skeletonic $GIT_TAG'
deploy:
  provider: releases
  api_key:
    secure: tV8YiXHvRLKVM2LwSahfe4yVhcQanMAd3Esx3j+AytnWqnXsFrulgsZnc4OLKvbWK8yiEa8AuNg4krqcd5E3i5lwrh0SScKayPu57g5SZIw9Y5bo1EkxV7Gr9kijffV3DnYXaw//z4ZhbbMud+aolyylPzrMjoGeY95ozJP1tx5uWrIEwU+Y9CrdeHiz788NTsXyUDZcrzC869lPpGjKa9AOnNi44pt2cPTKsmSFimvXL1vjE79UNz4tx9Ss1WQO6vwxvE+rol5/lUNJ3yfxp1lTluqvikdWSHiza6d6PwnSSKu/EDMuKuEi8vMvq+Ri+kBH60DAKXIBq8ByDxAGMobomGabsb55vA13gv+JlwsQI9tDtooCZ2p0QToOzPEHnbmhnB9Y/LmNlIE3vF0v6IKd6qzb9SqrNP+hflhx/5PvClmvakPVzgi5puqWBtpYYmXRv+tXjWVcb+AUHuL0p1SxMTCmyeI6r6GlXQxEQy2Ta1Grb9cZiXOaGHUtSbwSg89tAqRHVk79QwYKmG6JUnTG3YZgow4LANemTUvdNFpuaLHRU6eOzh7FLQi17bvddM+c81PCZfUEpE5+WcNzL45o4SKzxfNiWSMmPzkKLAJH5wdBaYl/QidrGbyOkmo5qD8IySyGtFGfqsXa+AqA1s3vx9D90ZbKtONSik+HEsA=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  name: Skeletonic $GIT_TAG
  body: "<strong>Change Log:</strong><br />Release $GIT_TAG created on $(date +'%d/%m/%Y')
    at $(date +'%T')<br />A sleek, lightweight, intuitive and ultra-responsive CSS
    framework. Designed to fit your web life."
  on:
    repo: reedia/skeletonic
before_install:
- openssl aes-256-cbc -K $encrypted_0da74458a2a7_key -iv $encrypted_0da74458a2a7_iv
  -in id_rsa.pub.enc -out id_rsa.pub -d
