language: node_js
node_js:
- 6
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: releases
  api_key:
    secure: COroxSGtJLNO3IG9HSGrQIeGb5TBBemK9SO10pCAulFPLcDbQgtmQMOcXOvmOKqqQg9fwhjfw562Nd2B1Qg0/G3A5lYpKXXukCe6T7c3FOWHp5ZoVm1AKQA0cYf4748z1kXh7r+AevXVnr2lTAP99vahCdd9PzUy7hcv2Hru/nn8t6wmQJj4dWlv9w+YfuNBxUYTfNl/TlRPnQjEYHsiPCl4UJdpsmekqB7HTOT+FhZ7KQQdMjxEbe6ayMVxnthGmowOfd5gvr9wZsWFPtv3zBd21b20RqJtWIzCJY/tBFJuV8CjczrBqYop5wTzbREEfW4N34P5FeZvpRYU0P2/3ojmtPFKScPMT+a/gafCsK67sRZNROBj3rIAJV26tJKcfQMJ7LZVAU+r4FzzZQRJyjn1N3DgqX5wyxFS/lnJ7al+6s3FPB2dOcTAssR040eCWjkdbp/4Aflz77JzDSnbel7bcq2vLAptn0qqaYe0BgAGsvKr9DqhWEigpncn26tXL2blUgmdGLnKxPugSavOFDyU0BnWpm2A28WjQxqak+8SuHkQ/0qOi5mEvEioDIgjMXLFwy56ZNlcQRhp59HOa8AjJqowqe7XCiRIAMdybl4amgPSKacNTV5e3uOFEUyqSLE3Hff71LUgDOLLicZ3LTFH6R1Ag3S9lWHDd4sZuvY=
  file: dist/skeletonic.min.css
  on:
    repo: reedia/skeletonic
env:
  global:
    secure: YFrLQXgisc/xmu0L3x2XvRsFzHtaJLfBiCOmO0fhMG02GutVTFelNaVjnl+5H8Wmgijm9qMCWvXMlVjK/NwyY7P+Wbop7/jkXKgl1uYiSH5zXUlEMzTgTS2F/JChegDhiO98MKDmSwY41S1wsLm4rCvWsr3QBHiLN533G4+UAsrX8Rr9JYNkEUwxbjjlT0oYhMkjkDT8JtuUEUAYhW394qNR607Sub0dKRSUdyRU3iyXvUpaaaNSDYQP+NcCIqGnG+g8ftYuz0H23ESwPP3hgCwV0aN48yIPUN1yyOFmiz+LCv9KP4/eYY7ghlnXJPUyqDjqPN4hYmDZQhplvlUBHX5OtX+7EqWF79IJHmOqD/0D5/BjHgLEhMYJH32Txze4EWpsAKB0wBjqhSR7jAdH9UckeYMyiM7OdwSr+Mh4r1pmDLlfQnqwH6qt3pGoeZl2QSZkiLoJBXN/faCN+jQ/dR/JPRGQ6CuaVy1kugxqBunsi3RlRKM4xAcp+WGEF4kIxG9O+0OGJf+FHVSCbpkp7JlGsovaUDxF2CdClNEB1WKIslvJk8w4aYCQ9+AGJAQfiIfVmuIhRzKrFmAzzPGkDt0I6tEQa/fdsIOzof0ES1nA4/xWcc/+npMzpycINs1xx+YKROPoUj/05ENhClmKAU1/aDaX50wiE6s/h2X4YNA=
